### ISSUE TITLE
Unable to register for acquiring the TechQA Dataset

### ISSUE THREAD

**Issue by abhi1nandy2** [IBM/techqa#1]
There is no `Sign up` link for registering for getting a login in order to get the TechQA Dataset. Could you please how I could get the dataset?

**Comment by vikas95** [comment]
Hi,

We had registered here (https://leaderboard.techqa.us-east.containers.appdomain.cloud/) by clicking on the "Login/Register" tab on the right upper corner.

**Comment by abhi1nandy2** [comment]
Thanks for the clarification!
